// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  openApiSidebar: [
    {
      type: "category",
      label: "REST API",
      link: {
        type: "generated-index",
        title: "ALGOPACK API",
        slug: "/api"
      },
      items: require("./docs/api/sidebar.js")
    },
    {
      type: "category",
      label: "WEBSOCKET",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "websocket/websocket",
          label: "Подключение к ISS+ через Websocket",
        },
        {
          type: "category",
          label: "Справочники WebSocket",
          collapsed: false,
          items: [
            {
              type: "doc",
              id: "websocket/docs/websocket-ru",
              label: "Справочник (ru)",
            },
            {
              type: "doc",
              id: "websocket/docs/websocket-en",
              label: "Справочник (en)",
            },
          ],
        },
      ],
    },
  ],

  descriptionSidebar: [
    {
      type: 'autogenerated',
      dirName: 'description',
    },
  ],

  datasetsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'modules',
    },
  ],

  methodologySidebar: [
    {
      type: 'autogenerated',
      dirName: 'method',
    },
  ],

  pythonSidebar: [
    {
      type: 'doc',
      id: 'python',
      label: 'Python',
    },
  ],

  contactsSidebar: [
    {
      type: 'doc',
      id: 'contacts',
      label: 'Обратная связь',
    },
  ],

  examplesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
  ],

};

export default sidebars;
